"""add_otp_requests_table

Revision ID: 4af134cf36cf
Revises: 8b2c3d4e5f67
Create Date: 2026-02-02 15:30:33.943050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4af134cf36cf'
down_revision: Union[str, Sequence[str], None] = '8b2c3d4e5f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commodities', 'growing_months',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment='Months when crop is grown [1-12]',
               existing_nullable=True)
    op.alter_column('commodities', 'harvest_months',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment='Months when crop is harvested [1-12]',
               existing_nullable=True)
    op.alter_column('commodities', 'peak_season_start',
               existing_type=sa.INTEGER(),
               comment='Start month of peak selling season (1-12)',
               existing_nullable=True)
    op.alter_column('commodities', 'peak_season_end',
               existing_type=sa.INTEGER(),
               comment='End month of peak selling season (1-12)',
               existing_nullable=True)
    op.alter_column('commodities', 'major_producing_states',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               comment='Top producing states for this commodity',
               existing_nullable=True)
    op.alter_column('mandis', 'operating_days',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               comment="Days of operation e.g. ['Monday', 'Tuesday', ...]",
               existing_nullable=True)
    op.alter_column('mandis', 'payment_methods',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               comment="Accepted payment methods e.g. ['Cash', 'UPI', 'Bank Transfer']",
               existing_nullable=True)
    op.alter_column('mandis', 'commodities_accepted',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               comment='List of commodity names accepted at this mandi',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mandis', 'commodities_accepted',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               comment=None,
               existing_comment='List of commodity names accepted at this mandi',
               existing_nullable=True)
    op.alter_column('mandis', 'payment_methods',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               comment=None,
               existing_comment="Accepted payment methods e.g. ['Cash', 'UPI', 'Bank Transfer']",
               existing_nullable=True)
    op.alter_column('mandis', 'operating_days',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               comment=None,
               existing_comment="Days of operation e.g. ['Monday', 'Tuesday', ...]",
               existing_nullable=True)
    op.alter_column('commodities', 'major_producing_states',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               comment=None,
               existing_comment='Top producing states for this commodity',
               existing_nullable=True)
    op.alter_column('commodities', 'peak_season_end',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='End month of peak selling season (1-12)',
               existing_nullable=True)
    op.alter_column('commodities', 'peak_season_start',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Start month of peak selling season (1-12)',
               existing_nullable=True)
    op.alter_column('commodities', 'harvest_months',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment=None,
               existing_comment='Months when crop is harvested [1-12]',
               existing_nullable=True)
    op.alter_column('commodities', 'growing_months',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment=None,
               existing_comment='Months when crop is grown [1-12]',
               existing_nullable=True)
    # ### end Alembic commands ###
